// <auto-generated />
using System;
using FinanceManager.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinanceManager.Repository.Migrations
{
    [DbContext(typeof(FinanceManagerDbContext))]
    [Migration("20200609075546_finalDBase")]
    partial class finalDBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rayaduboat")
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinanceManager.Model.Models.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BatchID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActualBatch")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int>("ShippersId")
                        .HasColumnName("ShippersID")
                        .HasColumnType("int");

                    b.HasKey("BatchId");

                    b.HasIndex("ShippersId");

                    b.ToTable("Batch","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.BatchLabel", b =>
                {
                    b.Property<int>("BatchLabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BatchLabelID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("date");

                    b.Property<string>("LabelCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("ShippersId")
                        .HasColumnName("ShippersID")
                        .HasColumnType("int");

                    b.HasKey("BatchLabelId");

                    b.HasIndex("ShippersId");

                    b.ToTable("BatchLabel","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.BookingMonitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Counter")
                        .HasColumnType("int");

                    b.Property<int>("LastId")
                        .HasColumnName("LastID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BookingMonitor","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.ClientUsage", b =>
                {
                    b.Property<int?>("NumOfRecipients")
                        .HasColumnType("int");

                    b.Property<int?>("NumOfTrips")
                        .HasColumnType("int");

                    b.Property<string>("RecName")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("RecTown")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<int>("RecipientId")
                        .HasColumnName("RecipientID")
                        .HasColumnType("int");

                    b.Property<string>("SendName")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("SendTown")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<int>("SenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SenderID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.ToTable("ClientUsage","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool?>("IsSelected")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Country","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Expenditure", b =>
                {
                    b.Property<int>("ExpenditureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ExpenditureID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Amount")
                        .HasColumnType("money");

                    b.Property<int?>("BatchId")
                        .HasColumnName("BatchID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ExpenseType")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("IsReceiptIssued")
                        .HasColumnType("char(5)")
                        .IsFixedLength(true)
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("ModeOfPayment")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ExpenditureId");

                    b.HasIndex("BatchId");

                    b.ToTable("Expenditure","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.ExpenditureReport", b =>
                {
                    b.Property<int>("ExpReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ExpReportID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActualBatch")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("Amount")
                        .HasColumnType("money");

                    b.Property<int?>("Batch")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ExpenseType")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("ModeOfPayment")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ExpReportId");

                    b.ToTable("ExpenditureReport","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.ExpenseItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ExpenseItems","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.ExpensePeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<string>("Period")
                        .HasColumnName("PERIOD")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ExpensePeriod","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.FreightAgent", b =>
                {
                    b.Property<int>("FreightAgentId")
                        .HasColumnName("FreightAgentID")
                        .HasColumnType("int");

                    b.Property<string>("AddressLineOne")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("AddressLineTwo")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("PostCode")
                        .HasColumnType("char(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Telephone")
                        .HasColumnType("char(20)")
                        .IsFixedLength(true)
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("TownCity")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("WebAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("FreightAgentId");

                    b.ToTable("FreightAgent","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.GhanaCities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GhanaCities","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Ghcity", b =>
                {
                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("int");

                    b.Property<bool?>("IsSelected")
                        .HasColumnType("bit");

                    b.ToTable("GHCity","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Income", b =>
                {
                    b.Property<int>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IncomeID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActualRef")
                        .HasColumnName("ActualRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("money");

                    b.Property<int?>("BatchId")
                        .HasColumnName("BatchID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("ModeOfPayment")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("IncomeId");

                    b.HasIndex("BatchId");

                    b.ToTable("Income","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Items", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ItemID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Colour")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Specifications")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("money");

                    b.HasKey("ItemId")
                        .HasName("PK__Item__727E83EBCB113D7C");

                    b.ToTable("Items","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.License", b =>
                {
                    b.Property<int>("LicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LicenseID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LicenceEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("LicenceStartDate")
                        .HasColumnType("date");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("NumberOfUsers")
                        .HasColumnType("int");

                    b.Property<string>("UserEmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("LicenseId");

                    b.ToTable("License","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nchar(200)")
                        .IsFixedLength(true)
                        .HasMaxLength(200);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nchar(200)")
                        .IsFixedLength(true)
                        .HasMaxLength(200);

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nchar(200)")
                        .IsFixedLength(true)
                        .HasMaxLength(200);

                    b.Property<string>("Role")
                        .HasColumnType("nchar(200)")
                        .IsFixedLength(true)
                        .HasMaxLength(200);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Login","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.PayMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<string>("Paymode1")
                        .HasColumnName("PAYMODE")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("PayMode","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountMonth")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("AccountPeriod")
                        .HasColumnType("int");

                    b.Property<string>("AccountYear")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("AcountDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("AditionalIncome")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("BatchId")
                        .HasColumnName("BatchID")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProfitLoss")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("ProfitLossPercent")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("TotalExpenditure")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("TotalIncome")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("Performance","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.PickingAddressList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLineOne")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("AddressLineTwo")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("PostCode")
                        .HasColumnType("char(20)")
                        .IsFixedLength(true)
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("PostTown")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("Telephone")
                        .HasColumnType("char(30)")
                        .IsFixedLength(true)
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.HasKey("Id");

                    b.ToTable("PickingAddressList","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.PickingAddressListRep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLineOne")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("AddressLineTwo")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("PostCode")
                        .HasColumnType("char(20)")
                        .IsFixedLength(true)
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("PostTown")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("Telephone")
                        .HasColumnType("char(30)")
                        .IsFixedLength(true)
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.HasKey("Id");

                    b.ToTable("PickingAddressListRep","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Recipients", b =>
                {
                    b.Property<int>("RecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RecipientID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLineOne")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("AddressLineTwo")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("County")
                        .HasColumnType("nchar(75)")
                        .IsFixedLength(true)
                        .HasMaxLength(75);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("PostCode")
                        .HasColumnType("char(20)")
                        .IsFixedLength(true)
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("PostTown")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<int>("SenderId")
                        .HasColumnName("SenderID")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasColumnType("char(30)")
                        .IsFixedLength(true)
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.HasKey("RecipientId")
                        .HasName("PK__Receiver__FEBB5F072C82413E");

                    b.HasIndex("SenderId");

                    b.HasIndex("FirstName", "LastName", "Telephone", "RecipientId")
                        .HasName("NonClusteredIndex-20140216-190105");

                    b.ToTable("Recipients","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.SenderRecipients", b =>
                {
                    b.Property<int>("RecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RecipientID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLineOne")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("AddressLineTwo")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("County")
                        .HasColumnType("nchar(75)")
                        .IsFixedLength(true)
                        .HasMaxLength(75);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("PostCode")
                        .HasColumnType("char(20)")
                        .IsFixedLength(true)
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("PostTown")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<int>("SenderId")
                        .HasColumnName("SenderID")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasColumnType("char(30)")
                        .IsFixedLength(true)
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.HasKey("RecipientId");

                    b.ToTable("SenderRecipients","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Senders", b =>
                {
                    b.Property<int>("SenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SenderID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLineOne")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("AddressLineTwo")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("County")
                        .HasColumnType("nchar(75)")
                        .IsFixedLength(true)
                        .HasMaxLength(75);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("PostCode")
                        .HasColumnType("char(20)")
                        .IsFixedLength(true)
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("PostTown")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<int>("ShippersId")
                        .HasColumnName("ShippersID")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasColumnType("char(30)")
                        .IsFixedLength(true)
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.HasKey("SenderId")
                        .HasName("PK__Sender__BB4991ABD1AAA538");

                    b.HasIndex("ShippersId");

                    b.ToTable("Senders","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Shippers", b =>
                {
                    b.Property<int>("ShippersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ShippersID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLineOne")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("AddressLineTwo")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("CompanyNumber")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<DateTime?>("Dob")
                        .HasColumnName("DOB")
                        .HasColumnType("date");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<int>("LicenseId")
                        .HasColumnName("LicenseID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnType("char(20)")
                        .IsFixedLength(true)
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("PostTown")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Telephone")
                        .HasColumnType("char(30)")
                        .IsFixedLength(true)
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("Vatnumber")
                        .IsRequired()
                        .HasColumnName("VATNumber")
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<string>("WebAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ShippersId");

                    b.HasIndex("LicenseId");

                    b.ToTable("Shippers","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.TripDetails", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TripID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActualRef")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("BatchId")
                        .HasColumnName("BatchID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("GrandTotal")
                        .HasColumnType("money");

                    b.Property<int?>("ItemId")
                        .HasColumnName("ItemID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("date");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RecipientId")
                        .HasColumnName("RecipientID")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnName("SenderID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("Total")
                        .HasColumnType("money");

                    b.HasKey("TripId");

                    b.HasIndex("BatchId");

                    b.HasIndex("ItemId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("TripDetails","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.TripListReport", b =>
                {
                    b.Property<int>("TripReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TripReportID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActualBatch")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("ActualRef")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("BatchId")
                        .HasColumnName("BatchID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("date");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnName("ItemID")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RecTown")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SendTown")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TelRecipient")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TelSender")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("Total")
                        .HasColumnType("money");

                    b.HasKey("TripReportId");

                    b.ToTable("TripListReport","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Ukcity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsSelected")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("UKCity","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users","Batches");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Batch", b =>
                {
                    b.HasOne("FinanceManager.Model.Models.Shippers", "Shippers")
                        .WithMany("Batch")
                        .HasForeignKey("ShippersId")
                        .HasConstraintName("FK_Batch_Shippers")
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceManager.Model.Models.BatchLabel", b =>
                {
                    b.HasOne("FinanceManager.Model.Models.Shippers", "Shippers")
                        .WithMany("BatchLabel")
                        .HasForeignKey("ShippersId")
                        .HasConstraintName("FK_BatchLabel_Shippers")
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Expenditure", b =>
                {
                    b.HasOne("FinanceManager.Model.Models.Batch", "Batch")
                        .WithMany("Expenditure")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("FK_Expenditure_Batch");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Income", b =>
                {
                    b.HasOne("FinanceManager.Model.Models.Batch", "Batch")
                        .WithMany("Income")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("FK_Income_Batch");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Performance", b =>
                {
                    b.HasOne("FinanceManager.Model.Models.Batch", "Batch")
                        .WithMany("Performance")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("FK_Performance_Batch");
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Recipients", b =>
                {
                    b.HasOne("FinanceManager.Model.Models.Senders", "Sender")
                        .WithMany("Recipients")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK_Recipients_Senders")
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Senders", b =>
                {
                    b.HasOne("FinanceManager.Model.Models.Shippers", "Shippers")
                        .WithMany("Senders")
                        .HasForeignKey("ShippersId")
                        .HasConstraintName("FK_Senders_Shippers")
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceManager.Model.Models.Shippers", b =>
                {
                    b.HasOne("FinanceManager.Model.Models.License", "License")
                        .WithMany("Shippers")
                        .HasForeignKey("LicenseId")
                        .HasConstraintName("FK_Shippers_License")
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceManager.Model.Models.TripDetails", b =>
                {
                    b.HasOne("FinanceManager.Model.Models.Batch", "Batch")
                        .WithMany("TripDetails")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("FK_TripDetails_Batch")
                        .IsRequired();

                    b.HasOne("FinanceManager.Model.Models.Items", "Item")
                        .WithMany("TripDetails")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK_TripDetails_Items");

                    b.HasOne("FinanceManager.Model.Models.Recipients", "Recipient")
                        .WithMany("TripDetails")
                        .HasForeignKey("RecipientId")
                        .HasConstraintName("FK_TripDetails_Recipients")
                        .IsRequired();

                    b.HasOne("FinanceManager.Model.Models.Senders", "Sender")
                        .WithMany("TripDetails")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK_TripDetails_Senders")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
